# Generated by Django 5.2.4 on 2025-07-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '블로그', 'verbose_name_plural': '블로그 목록'},
        ),
    ]
